import { AnalysisStats, Product, RiskDistribution } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Yaourt Nature Bio',
    sku: 'YNB-001',
    category: 'Produits laitiers',
    riskLevel: 'critical',
    daysOfCover: 15,
    capitalLocked: 450,
    stock: 150,
    recoveryValue: 225,
    action: 'Remise immediate -50%',
    lastUpdated: '2026-04-01',
  },
  {
    id: '2',
    name: 'Fromage Camembert',
    sku: 'FCM-002',
    category: 'Produits laitiers',
    riskLevel: 'critical',
    daysOfCover: 20,
    capitalLocked: 640,
    stock: 80,
    recoveryValue: 480,
    action: 'Don association',
    lastUpdated: '2026-04-01',
  },
  {
    id: '3',
    name: 'Salade Mesclun',
    sku: 'SML-003',
    category: 'Fruits & Legumes',
    riskLevel: 'high',
    daysOfCover: 45,
    capitalLocked: 135,
    stock: 45,
    recoveryValue: 90,
    action: 'Promotion flash',
    lastUpdated: '2026-04-01',
  },
  {
    id: '4',
    name: 'Poulet Fermier',
    sku: 'PFR-004',
    category: 'Viandes',
    riskLevel: 'high',
    daysOfCover: 60,
    capitalLocked: 420,
    stock: 30,
    recoveryValue: 300,
    action: 'Remise -30%',
    lastUpdated: '2026-04-01',
  },
  {
    id: '5',
    name: 'Pain de Mie Complet',
    sku: 'PMC-005',
    category: 'Boulangerie',
    riskLevel: 'high',
    daysOfCover: 75,
    capitalLocked: 240,
    stock: 120,
    recoveryValue: 180,
    action: 'Surveillance',
    lastUpdated: '2026-04-01',
  },
  {
    id: '6',
    name: 'Jus Orange Frais',
    sku: 'JOF-006',
    category: 'Boissons',
    riskLevel: 'high',
    daysOfCover: 80,
    capitalLocked: 600,
    stock: 200,
    recoveryValue: 400,
    action: 'Mise en avant',
    lastUpdated: '2026-04-01',
  },
  {
    id: '7',
    name: 'Conserve Tomates',
    sku: 'CTM-007',
    category: 'Epicerie',
    riskLevel: 'safe',
    daysOfCover: 365,
    capitalLocked: 1250,
    stock: 500,
    recoveryValue: 750,
    action: 'Aucune action',
    lastUpdated: '2026-04-01',
  },
  {
    id: '8',
    name: 'Riz Basmati',
    sku: 'RBS-008',
    category: 'Epicerie',
    riskLevel: 'safe',
    daysOfCover: 9999,
    capitalLocked: 750,
    stock: 300,
    recoveryValue: 450,
    action: 'Aucune action',
    lastUpdated: '2026-04-01',
  },
  {
    id: '9',
    name: 'Creme Fraiche',
    sku: 'CFR-009',
    category: 'Produits laitiers',
    riskLevel: 'high',
    daysOfCover: 55,
    capitalLocked: 180,
    stock: 60,
    recoveryValue: 120,
    action: 'Remise -25%',
    lastUpdated: '2026-04-01',
  },
  {
    id: '10',
    name: 'Saumon Fume',
    sku: 'SFM-010',
    category: 'Poissons',
    riskLevel: 'critical',
    daysOfCover: 10,
    capitalLocked: 625,
    stock: 25,
    recoveryValue: 375,
    action: 'Remise immediate -40%',
    lastUpdated: '2026-04-01',
  },
];

export const mockStats: AnalysisStats = {
  totalProducts: 1250,
  criticalProducts: 23,
  highProducts: 212,
  safeProducts: 1015,
  totalCapitalLocked: 125400,
  totalRecoveryValue: 45780,
  lastAnalysisDate: '2026-04-01T10:30:00',
};

export const mockRiskDistribution: RiskDistribution[] = [
  { level: 'critical', count: 23, percentage: 1.8 },
  { level: 'high', count: 212, percentage: 17.0 },
  { level: 'safe', count: 1015, percentage: 81.2 },
];
